packages:
  - apps/*
  - packages/*

catalog:
  '@testing-library/jest-dom': 7.0.0
  '@testing-library/react': 16.3.2
  '@types/mdast': 4.0.4
  '@types/node': 24.13.3
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.4
  happy-dom: 20.11.1
  react: 19.2.8
  react-dom: 19.2.8
  typescript: 7.0.2
  vite: 8.2.0
  vitest: 4.1.10

saveExact: true
minimumReleaseAge: 1440
allowBuilds:
  esbuild: true
  msw: false
  sharp: true
