packages:
  - apps/*
  - .github/actions/*
  - packages/*

catalog:
  '@testing-library/jest-dom': 7.0.1
  '@testing-library/react': 16.3.2
  '@types/mdast': 4.0.4
  '@types/node': 24.13.3
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.4
  esbuild: 0.28.2
  happy-dom: 20.11.6
  react: 19.2.8
  react-dom: 19.2.8
  sharp: 0.35.3
  typescript: 7.0.2
  vite: 8.2.2
  vitest: 4.1.11

overrides:
  '@types/node@': 'catalog:'
  '@types/react@': 'catalog:'

saveExact: true
minimumReleaseAge: 1440
allowBuilds:
  esbuild: true
  msw: false
  sharp: true
