# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

references:
  node_container_config: &node_container_config
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/workspace

  gcloud_container_config: &gcloud_container_config
    docker:
      - image: google/cloud-sdk
    working_directory: ~/workspace

jobs:
  web-build:
    <<: *node_container_config
    steps:
      - checkout
      # Install and cache dependencies
      - restore_cache:
          keys:
            - v1-web-dependencies-{{ checksum "web/package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-web-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
          working_directory: web
      - save_cache:
          paths:
            - node_modules
          key: v1-web-dependencies-{{ checksum "web/package-lock.json" }}
      # Build
      - run:
          name: Nuxt bulid
          command: npm run build
          working_directory: web
      # Set .env for Contentful CDA Access Token
      - run:
          name: Set .env
          command: echo CTF_CDA_ACCESS_TOKEN = $CTF_CDA_ACCESS_TOKEN > .env
          working_directory: web
      # Persist to workspace
      - persist_to_workspace:
          root: .
          paths:
            - web

  web-deploy:
    <<: *gcloud_container_config
    steps:
      - attach_workspace:
            at: .
      - run:
          name: Store GCP Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Initialize Google Cloud SDK
          command: |
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project ${GCLOUD_PROJECT}
      - run:
          name: Deploy to Google App Engine
          command: gcloud app deploy
          working_directory: web

  api-deploy:
    <<: *node_container_config
    steps:
      - checkout
      # Install and cache dependencies
      - restore_cache:
          keys:
            - v1-api-dependencies-{{ checksum "api/functions/package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-api-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
          working_directory: api/functions
      - save_cache:
          paths:
            - node_modules
          key: v1-api-dependencies-{{ checksum "api/functions/package-lock.json" }}
      - run:
          name: Install Firebase CLI
          command: npm add -D firebase-tools@latest
          working_directory: api/functions
      - run:
          name: Store Firebase Service key
          command: echo $GCLOUD_SERVICE_KEY > serviceAccountKey.json
          working_directory: api/functions
      - run:
          name: Set Firebase Functions Environment variabeles
          command: |
            ./node_modules/.bin/firebase functions:config:set fcm.serverkey=$FCM_SERVER_KEY
            ./node_modules/.bin/firebase functions:config:set contentful.cdaaccesstoken=$CTF_CDA_ACCESS_TOKEN
            ./node_modules/.bin/firebase functions:config:set basicauth.user=$BASIC_AUTH_USER
            ./node_modules/.bin/firebase functions:config:set basicauth.password=$BASIC_AUTH_PASSWORD
          working_directory: api/functions
      - run:
          name: Make Empty public directory
          command: mkdir public
          working_directory: api
      - run:
          name: Deploy to Cloud Functions for Firebase
          command: ./node_modules/.bin/firebase deploy --project "$GCLOUD_PROJECT" --token "$FIREBASE_TOKEN"
          working_directory: api/functions

workflows:
  version: 2
  build-deploy:
    jobs:
      - web-build
      - web-deploy:
          requires:
            - web-build
          filters:
            branches:
              only: master
      - api-deploy:
          filters:
            branches:
              only: master
